name: protein-prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - certifi=2024.2.2
  - colorama=0.4.6
  - contourpy=1.2.1
  - cycler=0.12.1
  - exceptiongroup=1.2.0
  - fonttools=4.53.0
  - freetype=2.12.1
  - iniconfig=2.0.0
  - joblib=1.4.2
  - kiwisolver=1.4.5
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=17.0.6
  - libdeflate=1.20
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libsqlite=3.45.3
  - libtiff=4.6.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libzlib=1.3.1
  - llvm-openmp=18.1.6
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - munkres=1.1.4
  - ncurses=6.5
  - networkx=3.3
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.1
  - packaging=24.0
  - pandas=2.2.2
  - pillow=10.3.0
  - pip=24.0
  - pluggy=1.5.0
  - pthread-stubs=0.4
  - pyparsing=3.1.2
  - pytest=8.2.2
  - python=3.12.3
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytz=2024.1
  - readline=8.2
  - scikit-learn=1.5.0
  - scipy=1.13.1
  - setuptools=70.0.0
  - six=1.16.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tomli=2.0.1
  - tornado=6.4
  - tzdata=2024a
  - wheel=0.43.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zstd=1.5.6
  - pip:
      - anyio==4.4.0
      - appnope==0.1.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.2.0
      - babel==2.15.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - comm==0.2.2
      - debugpy==1.8.2
      - decorator==5.1.1
      - defusedxml==0.7.1
      - executing==2.0.1
      - fastjsonschema==2.20.0
      - fqdn==1.5.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - idna==3.7
      - ipykernel==6.29.4
      - ipython==8.25.0
      - ipywidgets==8.1.3
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.2
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.1
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.2
      - jupyterlab-widgets==3.0.11
      - lab==8.2
      - markupsafe==2.1.5
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.2.1
      - notebook-shim==0.2.4
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - platformdirs==4.2.2
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycparser==2.22
      - pygments==2.18.0
      - python-json-logger==2.0.7
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - referencing==0.35.1
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.18.1
      - send2trash==1.8.3
      - simplejson==3.19.2
      - sniffio==1.3.1
      - soupsieve==2.5
      - stack-data==0.6.3
      - terminado==0.18.1
      - tinycss2==1.3.0
      - traitlets==5.14.3
      - txt2tags==3.9
      - types-python-dateutil==2.9.0.20240316
      - uri-template==1.3.0
      - urllib3==2.2.2
      - wcwidth==0.2.13
      - webcolors==24.6.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.11