name: Python application test with Conda

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  # example-3:
  #   name: Ex3 Linux
  #   runs-on: "ubuntu-latest"
  #   defaults:
  #     run:
  #       shell: bash -el {0}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: conda-incubator/setup-miniconda@v3
  #       with:
  #         activate-environment: protein-prediction
  #         environment-file: environment.yml
  #         python-version: 3.8  # Correct the Python version here
  #         auto-activate-base: false
  #         channels: conda-forge, defaults
  #     - run: |
  #         conda info
  #         conda list
  conda-only:
    name: Test conda environment
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: protein-prediction
          environment-file: environment.yml
          auto-activate-base: false
          miniconda-version: "latest"
      # Log conda environment contents
      - name: Log conda environment
        shell: bash --login {0}
        run: conda list
