name: Python application test with Conda

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.12.3   # Change this to your desired Python version
        environment-file: environment.yml
        activate-environment: protein-prediction  # Name of your conda environment as specified in environment.yml

    - name: Install dependencies
      run: conda env update --file environment.yml --name protein-prediction

    - name: Run tests
      run: |
        source activate myenv
        pytest