name: Python application test with Conda

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  example-3:
    name: Ex3 Linux
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: protein-prediction
          environment-file: environment.yml
          python-version: 3.12.3
          auto-activate-base: false
          channels: conda-forge,defaults, gurobi

      - run: |
          conda info
          conda list
